feat:Advantages of TypeScript(#39520)
Rajshrishrimalshah/javascript-server pull request #6
Opened 2019-04-26 05:00 UTC by Rajshrishrimalshah

please review my assignment.

2019-04-26 08:47 UTC, SunilSuccessive requested changes

2019-04-26 08:47 UTC, SunilSuccessive commented on extra/constant.js
> +export const users = [
Please specify the variable types everywhere because you are writing ts not js

2019-04-26 08:47 UTC, SunilSuccessive commented on extra/index.js
> + import { diamond,equilateral } from "./patterns"
please use proper spacing

2019-04-26 08:47 UTC, SunilSuccessive commented on extra/index.js
> + import {PERMISSION_ALL,PERMISSION_READ,PERMISSION_WRITE,PERMISSION_DELETE,
Please use proper spacing

2019-04-26 08:47 UTC, SunilSuccessive commented on extra/patterns/diamond.js
> +export const diamond = (max) => {
please define types of function everywhere

2019-04-26 10:45 UTC, Rajshrishrimalshah commented on extra/index.js
> + import {PERMISSION_ALL,PERMISSION_READ,PERMISSION_WRITE,PERMISSION_DELETE,
done

2019-04-26 10:45 UTC, Rajshrishrimalshah commented on extra/index.js
> + import { diamond,equilateral } from "./patterns"
done

2019-04-29 06:23 UTC, Rajshrishrimalshah commented on extra/constant.js
> +export const users = [
done.

2019-04-29 06:26 UTC, Rajshrishrimalshah commented on extra/patterns/diamond.js
> +export const diamond = (max) => {
done.

2019-04-29 08:43 UTC, SunilSuccessive commented on extraTs/constant.ts
> +export const users = [
Define types of users object

2019-04-29 08:43 UTC, SunilSuccessive commented on extraTs/interfaces.ts
> +export interface Ipattern {
P should be capital in Ipattern.
Naming Convention for interface: -
 - Use pascal case
 - Start with I
 - Use meaningful variable or method name.
 - e.g., method name is pattern and interface should be IPattern.

2019-04-29 09:24 UTC, Rajshrishrimalshah commented on extraTs/interfaces.ts
> +export interface Ipattern {
done.

2019-04-29 09:43 UTC, Rajshrishrimalshah commented on extraTs/constant.ts
> +export const users = [
done.

2019-04-29 10:01 UTC, merged